// <auto-generated />
using System;
using DL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20200421071001_Init1")]
    partial class Init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DL.Entities.Homework", b =>
                {
                    b.Property<int>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HomeworkDate");

                    b.Property<int>("HomeworkMark");

                    b.Property<int?>("HomeworkStudentStudentId");

                    b.Property<int?>("HomeworkTeacherTeacherId");

                    b.HasKey("HomeworkId");

                    b.HasIndex("HomeworkStudentStudentId");

                    b.HasIndex("HomeworkTeacherTeacherId");

                    b.ToTable("Homework");
                });

            modelBuilder.Entity("DL.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentName");

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DL.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherName");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("DL.Entities.Homework", b =>
                {
                    b.HasOne("DL.Entities.Student", "HomeworkStudent")
                        .WithMany("Homeworks")
                        .HasForeignKey("HomeworkStudentStudentId");

                    b.HasOne("DL.Entities.Teacher", "HomeworkTeacher")
                        .WithMany("Homeworks")
                        .HasForeignKey("HomeworkTeacherTeacherId");
                });
#pragma warning restore 612, 618
        }
    }
}
